# Pulling Data using DarkSky API

Required librarires

In [1]:
import requests
import pandas as pd
import datetime

In [6]:
i = 0 #initialize counter
#final-time 1533115500
#stopped-time 1525376400
#starting-time 1521061200
loop = (1525376400-1521061200)/300
print(loop)

14384.0

## First data

Pulling the first data is useful for checking the right format before large amount pulling.

In [7]:
initial_time = 1525376400 #this is the starting time in UNIX format
timestamp = initial_time + 300*i #next request is after 5 minutes
url = 'https://api.darksky.net/forecast/6829167db76975d957b2149428e13801/39.8906,32.7817,' 
url = url + str(timestamp)
data = requests.get(url) #data returned in json format
data=data.json() #opening json 

#Sometimes there may be some missing values from Darksky. Try-except blocks is useful for stopping issues about KeyError

try:
    cloudCover= data['currently']['cloudCover']
except KeyError:
    cloudCover = None  
try:
    temp= data['currently']['apparentTemperature']
except KeyError:
    temp = None
try:
    humidity = data['currently']['humidity']
except KeyError:
    humidity = None
try:
    icon = data['currently']['icon']
except KeyError:
    icon = None
try:
    windSpeed = data['currently']['windSpeed']
except KeyError:
    windSpeed = None
try:
    visibility = data['currently']['visibility']
except KeyError:
    visibility = None
try:
    windBearing = data['currently']['windBearing']
except KeyError:
    windBearing = None
try:
    pressure = data['currently']['pressure']
except KeyError:
    pressure = None
try:
    dewPoint = data['currently']['dewPoint']
except KeyError:
    dewPoint = None

row = {'cloudCover':cloudCover , 'temp' : temp , 'humidity' : humidity , 'icon' : icon,'windSpeed' : windSpeed , 'visibility' : visibility, 'windBearing' : windBearing ,'pressure' : pressure ,"dewPoint" : dewPoint}
time_index = datetime.datetime.fromtimestamp(int(timestamp)).strftime('%Y-%m-%d %H:%M:%S')
df2 = pd.DataFrame(data=row,index=[timestamp])

In [8]:
df2

,cloudCover,dewPoint,humidity,icon,pressure,temp,visibility,windBearing,windSpeed
1525376400,0.42,45.49,0.51,partly-cloudy-night,1009.87,63.93,6.22,100,1.82

## For loop

In [9]:
for i in range (0,int(loop)): #one
    initial_time = 1525376400
    timestamp = initial_time + 300*i #5 minute
    url = 'https://api.darksky.net/forecast/18971c55f948a8d2261f41457e4db0cb/39.8906,32.7817,' 
    url = url + str(timestamp)
    data = requests.get(url)
    data=data.json()
    try:
        cloudCover= data['currently']['cloudCover']
    except KeyError:
        cloudCover = None  
    try:
        temp= data['currently']['apparentTemperature']
    except KeyError:
        temp = None
    try:
        humidity = data['currently']['humidity']
    except KeyError:
        humidity = None
    try:
        icon = data['currently']['icon']
    except KeyError:
        icon = None
    try:
        windSpeed = data['currently']['windSpeed']
    except KeyError:
        windSpeed = None
    try:
        visibility = data['currently']['visibility']
    except KeyError:
        visibility = None
    try:
        windBearing = data['currently']['windBearing']
    except KeyError:
        windBearing = None
    try:
        pressure = data['currently']['pressure']
    except KeyError:
        pressure = None
    try:
        dewPoint = data['currently']['dewPoint']
    except KeyError:
        dewPoint = None

    row = {'cloudCover':cloudCover , 'temp' : temp , 'humidity' : humidity , 'icon' : icon,'windSpeed' : windSpeed , 'visibility' : visibility, 'windBearing' : windBearing ,'pressure' : pressure ,"dewPoint" : dewPoint}
    time_index = datetime.datetime.fromtimestamp(int(timestamp)).strftime('%Y-%m-%d %H:%M:%S')
    df = pd.DataFrame(data=row,index=[timestamp])
    df2 = df2.append(df)
df2.to_csv('sonpull2.csv')

In [1]:
df2

NameError: name 'df2' is not defined

## Dataframe to CSV

In [32]:
df2.to_csv('sonpull.csv')

In [17]:
df2

,cloudCover,dewPoint,humidity,ozone,pressure,temp,uvIndex,visibility,windBearing,windGust,windSpeed
2018-03-17 01:55:00,0.74,36.99,0.68,None,1014.62,45.99,0,6.22,148,8.16,3.50
2018-03-15 00:00:00,0.38,37.61,0.79,None,1010.95,42.42,0,6.22,238,7.99,3.03
2018-03-15 00:05:00,0.38,37.57,0.79,None,1010.93,43.59,0,6.22,237,7.99,2.99
2018-03-15 00:10:00,0.39,37.53,0.79,None,1010.92,43.56,0,6.22,236,7.99,2.95
2018-03-15 00:15:00,0.39,37.49,0.79,None,1010.91,43.53,0,6.22,234,7.99,2.91
2018-03-15 00:20:00,0.40,37.45,0.79,None,1010.90,43.51,0,6.22,233,7.99,2.87
2018-03-15 00:25:00,0.40,37.41,0.79,None,1010.88,43.48,0,6.22,232,7.99,2.84
2018-03-15 00:30:00,0.41,37.37,0.79,None,1010.87,43.46,0,6.22,231,7.99,2.80
2018-03-15 00:35:00,0.41,37.33,0.79,None,1010.86,43.43,0,6.22,229,7.99,2.77
2018-03-15 00:40:00,0.42,37.29,0.79,None,1010.85,43.40,0,6.22,228,7.99,2.74
2018-03-15 00:45:00,0.42,37.25,0.79,None,1010.84,43.38,0,6.22,226,7.99,2.71
2018-03-15 00:50:00,0.43,37.22,0.79,None,1010.82,43.35,0,6.22,225,7.99,2.68
2018-03-15 00:55:00,0.43,37.18,0.79,None,1010.81,43.33,0,6.22,224,7.99,2.65
2018-03-15 01:00:00,0.44,37.14,0.79,None,1010.80,43.30,0,6.22,222,7.99,2.62
2018-03-15 01:05:00,0.44,37.13,0.79,None,1010.83,43.26,0,6.22,222,7.99,2.60
2018-03-15 01:10:00,0.44,37.12,0.79,None,1010.87,43.22,0,6.22,222,7.99,2.58
2018-03-15 01:15:00,0.44,37.11,0.79,None,1010.90,43.18,0,6.22,222,7.99,2.56
2018-03-15 01:20:00,0.44,37.10,0.79,None,1010.94,43.14,0,6.22,222,7.99,2.54
2018-03-15 01:25:00,0.44,37.09,0.79,None,1010.97,43.10,0,6.22,222,7.99,2.52
2018-03-15 01:30:00,0.44,37.08,0.79,None,1011.00,43.06,0,6.22,222,7.99,2.50
2018-03-15 01:35:00,0.44,37.06,0.79,None,1011.04,43.02,0,6.22,222,7.99,2.48
2018-03-15 01:40:00,0.44,37.05,0.79,None,1011.07,42.98,0,6.22,221,7.99,2.46
2018-03-15 01:45:00,0.44,37.04,0.80,None,1011.11,42.93,0,6.22,221,7.99,2.44
2018-03-15 01:50:00,0.44,37.03,0.80,None,1011.14,42.89,0,6.22,221,7.99,2.42
2018-03-15 01:55:00,0.44,37.02,0.80,None,1011.18,42.85,0,6.22,221,7.99,2.40
2018-03-15 02:00:00,0.44,37.01,0.80,None,1011.21,42.81,0,6.22,221,7.99,2.38
2018-03-15 02:05:00,0.44,36.95,0.80,None,1011.19,42.69,0,6.22,220,7.82,2.23
2018-03-15 02:10:00,0.45,36.90,0.80,None,1011.16,42.57,0,6.22,219,7.66,2.08
2018-03-15 02:15:00,0.45,36.84,0.80,None,1011.14,42.45,0,6.22,218,7.49,1.93
2018-03-15 02:20:00,0.45,36.78,0.81,None,1011.12,42.32,0,6.22,216,7.33,1.78
...,...,...,...,...,...,...,...,...,...,...,...
2018-03-16 23:30:00,0.59,36.00,0.65,None,1014.92,47.24,0,6.22,147,7.50,1.28
2018-03-16 23:35:00,0.59,35.98,0.65,None,1014.91,47.25,0,6.22,147,7.42,1.25
2018-03-16 23:40:00,0.58,35.97,0.65,None,1014.90,47.26,0,6.22,146,7.34,1.22
2018-03-16 23:45:00,0.58,35.95,0.65,None,1014.89,47.27,0,6.22,145,7.26,1.18
2018-03-16 23:50:00,0.57,35.93,0.65,None,1014.87,47.28,0,6.22,144,7.18,1.15
2018-03-16 23:55:00,0.57,35.92,0.64,None,1014.86,47.29,0,6.22,143,7.09,1.12
2018-03-17 00:00:00,0.56,35.90,0.64,None,1014.85,47.30,0,6.22,142,7.01,1.09
2018-03-17 00:05:00,0.57,35.87,0.64,None,1014.84,47.29,0,6.22,145,7.26,1.18
2018-03-17 00:10:00,0.57,35.85,0.64,None,1014.83,47.29,0,6.22,149,7.51,1.27
2018-03-17 00:15:00,0.58,35.83,0.64,None,1014.81,47.28,0,6.22,152,7.76,1.36
2018-03-17 00:20:00,0.58,35.80,0.64,None,1014.80,47.27,0,6.22,155,8.01,1.46
2018-03-17 00:25:00,0.59,35.78,0.64,None,1014.79,47.26,0,6.22,157,8.26,1.56
2018-03-17 00:30:00,0.59,35.75,0.64,None,1014.78,47.26,0,6.22,159,8.51,1.66
2018-03-17 00:35:00,0.60,35.73,0.64,None,1014.76,47.25,0,6.22,161,8.76,1.76
2018-03-17 00:40:00,0.60,35.70,0.64,None,1014.75,47.24,0,6.22,162,9.01,1.86
2018-03-17 00:45:00,0.61,35.68,0.64,None,1014.74,47.23,0,6.22,163,9.26,1.97
2018-03-17 00:50:00,0.61,35.65,0.64,None,1014.73,47.23,0,6.22,165,9.51,2.08
2018-03-17 00:55:00,0.62,35.63,0.64,None,1014.72,47.22,0,6.22,166,9.76,2.19
2018-03-17 01:00:00,0.63,35.60,0.64,None,1014.70,47.21,0,6.22,167,10.01,2.29
2018-03-17 01:05:00,0.64,35.73,0.64,None,1014.70,47.20,0,6.22,164,9.84,2.39
2018-03-17 01:10:00,0.65,35.86,0.65,None,1014.69,47.20,0,6.22,162,9.67,2.49
2018-03-17 01:15:00,0.66,35.99,0.65,None,1014.68,47.19,0,6.22,160,9.50,2.59
2018-03-17 01:20:00,0.67,36.12,0.65,None,1014.67,47.19,0,6.22,158,9.33,2.70
2018-03-17 01:25:00,0.68,36.24,0.66,None,1014.66,47.18,0,6.22,156,9.17,2.80
2018-03-17 01:30:00,0.69,36.37,0.66,None,1014.66,47.17,0,6.22,155,9.00,2.91
2018-03-17 01:35:00,0.70,36.49,0.66,None,1014.65,46.45,0,6.22,153,8.83,3.03
2018-03-17 01:40:00,0.71,36.62,0.67,None,1014.64,46.33,0,6.22,152,8.66,3.14
2018-03-17 01:45:00,0.72,36.74,0.67,None,1014.63,46.21,0,6.22,151,8.49,3.26
2018-03-17 01:50:00,0.73,36.86,0.67,None,1014.62,46.10,0,6.22,149,8.33,3.38
2018-03-17 01:55:00,0.74,36.99,0.68,None,1014.62,45.99,0,6.22,148,8.16,3.50